// Rebuilds src/psl.js from the public suffix list. Run with: node tools/update-psl.mjs
// Reads the list from the file given as the first argument, or else from publicsuffix.org.
import { readFileSync, writeFileSync } from 'node:fs';
import { domainToASCII } from 'node:url';

const SOURCE = 'https://publicsuffix.org/list/public_suffix_list.dat';
const file = process.argv[2];
const text = file ? readFileSync(file, 'utf8') : await (await fetch(SOURCE)).text();

const version = text.match(/^\/\/ VERSION: (\S+)/m)?.[1];
const commit = text.match(/^\/\/ COMMIT: (\S+)/m)?.[1];
if (!version || !commit) throw new Error('not the public suffix list: no version in it');

// A rule is the first word of a line; host names reach the extension in their ASCII form.
const rules = new Set();
for (const line of text.split('\n')) {
  const rule = line.split(/\s/)[0];
  if (!rule || rule.startsWith('//')) continue;
  const [, mark, name] = rule.match(/^(!|\*\.)?(.+)$/);
  const ascii = domainToASCII(name);
  if (!ascii || ascii.includes('*')) throw new Error(`cannot read the rule "${rule}"`);
  rules.add((mark || '') + ascii);
}
if (rules.size < 9000) throw new Error(`only ${rules.size} rules: the list looks cut short`);

const lines = [];
let row = '';
for (const rule of [...rules].sort()) {
  if (row.length + rule.length > 110) {
    lines.push(row);
    row = '';
  }
  row += (row ? ' ' : '') + rule;
}
lines.push(row);

writeFileSync(new URL('../src/psl.js', import.meta.url), `// The public suffix list: the names under which unrelated parties register their own
// (co.uk, github.io), which says where the site in a host name starts.
// Generated by tools/update-psl.mjs from ${SOURCE}
// (version ${version}, commit ${commit}). Do not edit by hand.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// One rule per word, as in the list: "*." in front covers every name one level below,
// "!" marks an exception to such a rule. Names are in their ASCII (punycode) form.
globalThis.HNPF_PSL = \`
${lines.join('\n')}
\`;
`);
console.log(`src/psl.js: ${rules.size} rules, version ${version}`);
